#!/bin/bash
# For disk partition
# Give correct device name /dev/sda or /dev/nvme0n1 as example

sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk /dev/nvme0n1
  g # Create GPT disklabel
  n # New partition
  1 # Partition number 1
    # Default start of disk
  +1G # 1 GB boot parttion
  t # Partition type
  1 # EFI SYSTEM
  n # Sew partition
  2 # Partition number 2
    # Default after first block
  +100MB # Space Swap partition
  t # Type
  19 # Swap partition
  n # New partition
  3 # Partition number 3
    # Default after second block
  +5G # Space Root partition
  t # Type
  23 # Root x82-64
  n # New partition
  4 # partition number 4
    # Default after third block
    # Fulldisk
  t # Type
  42 # home
  w # write to disk
  q # quite

EOF
